name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # don't print dotnet logo
  DOTNET_NOLOGO: true

  # disable telemetry (reduces dotnet tool output in logs)
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-bicep:
    runs-on: ${{ matrix.os }}

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false

      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        include:
        - os: 'windows-latest'
          rid: 'win-x64'
          configuration: 'release'
          exe-suffix: '.exe'
        - os: 'ubuntu-latest'
          rid: 'linux-x64'
          configuration: 'release'
          exe-suffix: ''
        - os: 'macos-latest'
          rid: 'osx-x64'
          configuration: 'release'
          exe-suffix: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: buildcli
        uses: ./.github/actions/build-cli.yml
        with:
          rid: ${{ matrix.rid }}
          configuration: ${{ matrix.configuration }}
          exe-suffix: ${{ matrix.exe-suffix }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: bicep_${{ matrix.configuration }}_${{ matrix.rid }}
          path: ${{ steps.buildcli.outputs.publish-path }}/*
          if-no-files-found: error

  build-vscode:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: buildcli
        uses: ./.github/actions/build-vsix.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-bicep
          path: ${{ steps.buildcli.outputs.vsix-path }}
          if-no-files-found: error

  build-playground:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: buildcli
        uses: ./.github/actions/build-playground.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-bicep
          path: ${{ steps.buildcli.outputs.dist-path }}/*
          if-no-files-found: error